---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Beaverdown2: A Bioinformatics Workflow Management Package

[中文](https://github.com/rainoffallingstar/beaverdown2/blob/master/README_zh.md) ｜ [NotebookLLM](https://notebooklm.google.com/notebook/67b24f6c-2f7c-40b4-9019-c68f6b391948/audio)

## Introduction

`Beaverdown2` is an R-based bioinformatics workflow management package designed to simplify and automate complex bioinformatics analysis pipelines. It integrates R6 classes and the Snakemake workflow engine, supports multiple analysis modes (such as RRBS, WGBS, and RNAseq), and can run in various computing environments (e.g., Kubernetes, Slurm, and containerized environments). With `Beaverdown2`, users can easily configure, manage, and execute bioinformatics analysis tasks, including support for PDX/CDX (Patient/Cancer Cell Line Derived Xenograft) analysis pipelines.

## Features

### Core Features

1.  **Multi-Mode Support**
    -   RRBS (Reduced Representation Bisulfite Sequencing)
    -   WGBS (Whole Genome Bisulfite Sequencing)
    -   RNAseq (RNA Sequencing)
    -   PDX/CDX (Patient/Cancer Cell Line Derived Xenograft) analysis pipeline
2.  **Multi-Environment Support**
    -   Kubernetes
    -   Slurm
    -   Containerized environments (e.g., Docker)
3.  **Automated Workflow Management**
    -   Automatic generation of configuration files
    -   Automatic creation of necessary directory structures
    -   Support for multi-step workflows (e.g., data preprocessing, alignment, analysis)
4.  **Rich Tool Integration**
    -   Bismark, HTSeq, FastQC, Qualimap, etc.
    -   Support for XenofilteR for PDX/CDX data analysis
    -   Support for Methrix and scMethrix for methylation analysis and RRBS data imputation
5.  **Result Aggregation and Download**
    -   Automatic aggregation of analysis results
    -   Support for compressed downloads (e.g., ZIP or GZIP)
6.  **Notifications and Logging**
    -   Email notifications for task progress
    -   Detailed logging of workflow execution

### Additional Features

-   **Memory and CPU Detection**
    -   Functions to detect memory and CPU core usage in the current session.
-   **File Operations**
    -   Support for file compression, aggregation, and remote synchronization.
-   **DNA Sequence Manipulation**
    -   Functions to compute the reverse complement of DNA sequences.

## Installation

### Install from GitHub

``` r
pak::pak("Rhtslib")
pak::pak('CompEpigen/methrix')
pak::pak('CompEpigen/scMethrix')
pak::pak("BiocParallel")
pak::pak("NKI-GCF/XenofilteR")
pak::pak("rainoffallingstar/beaverdown2")
```

### **Dependencies**

`Beaverdown2` requires the following dependencies:

-   R version 4.0 or higher

-   Conda (for environment management; we provide a native function `beaverflow_install` to initialize the Conda environment)

-   Docker (if using Kubernetes or the pre-built container environment `fallingstar10/beaverstudio:latest`)

After installation, configure the workflow directory and environment by running:

```         
library(Beaverdown2) 

beaverflow_install(workflow_dir = "/path/to/your/workflow_dir", build_env = TRUE)
```

When Conda envs is built, [download the refer Genomic files](https://pan.quark.cn/s/e0908b382183) we provide under `inst/`, or a self-build of bismark/STAR-required refer Genomic files is suggested.These file dirs is required in `BeaverGandalf$new()`, these params are `genomeFile,gnome_fasta,cgGR_gz,CGI,rnaseq_gtf,rnaseq_ref`

``` bash
inst
├── Entrez_Gene_Id_db.RDS
├── hg19
│   ├── hg19_cpgIsland.bed # cgGR_gz
│   ├── hg19_CpG_sites.gz # CGI
├── pdx # genomeFile c("human","mouse)
│   ├── homo_sapiens
│   │   └── hg19.fasta #gnome_fasta c(".../.fasta",".../.fasta")
│   └── mouse
│       ├── GRCm38.fasta
├── rnaseq
    └── homo_sapiens # rnaseq_ref
       ├── hg19.ensGene.gtf 
       ├── hg19.ensGene_sorted.gtf # rnaseq_gtf
       ├── hg19.fasta
       
```

When `BeaverGandalf` is created, the result dirs will be created in the `{userspace}/{jobid}`(also params of `BeaverGandalf$new()`) by `gandalf_create_filework` method.

``` bash
{jobid}
├── QC
│   ├── multiqc_report.html
├── config
├── data
├── log
├── analysis
├── workflow
    ├── log
    ├── mCall
    ├── bsmap
    ├── fastqc_clean
    ├── fastqc_raw
    ├── QC
    ├── trim
    ├── uxm
    ├── clubcpg
    ├── mhap
    ├── RData
```

## **Usage**

### **Initialize Workflow**

``` r
library(beaverdown2) 

# in detail

gandalf_RRBS <- BeaverGandalf$new(
Mode = "RRBS", 
species1 = "human",     
species2 = "mouse", # if species2 is not NULL,PDX mode is used and graft and host params will work
graft = "human",
host = "mouse",
error = 0.2, adapter1 = "AGATCGGAAGAGC",adapter2 = "AGATCGGAAGAGC", C1 = 0,C2 = 0,T1 = 0,T2 = 0, # default params for trim adapters
read1_5 = 0,read1_3 = 0,read2_5 = 0,read2_3 = 0,seq_deth = 10, # default params for clubcpg, clubcpg will be used in future development. 
suffix1 = "_R1.fastq.gz" # use "_R1.fastq.gz" is now suggested to name the original fastq files, suffix2 will be computed
uploadfile = use_sever_fastq(serverpath = "/project/PDX_COAD_STAD"),  # dirs to fastq folder and generate a data.frame for input   
pdata = use_server_pdata(serverpath = "/config/20240923.xlsx"),   # pdata of samples includeing at least 2 col : sampleid,inline_barcode_sequence 
workflow_endpoint = "3", # 1 for fastq QC; 2 for mapping ; 3 for expression/methylation matrix    
user_email = "whoami@qq.com", # email needs additional setting
userspace = "userspace",userid = NULL,new_userid_always = T # default setting of Result dirs, userid is generated randomly if NULL,use current jobid if new_userid_always is FALSE
)

# in short

gandalf_RRBS <- BeaverGandalf$new(
Mode = "RRBS", 
species1 = "human",     
species2 = "mouse", # if species2 is not NULL,PDX mode is used and graft and host params will work
graft = "human",
host = "mouse",
uploadfile = use_sever_fastq(serverpath = "/project/PDX_COAD_STAD"),  # dirs to fastq folder and generate a data.frame for input   
pdata = use_server_pdata(serverpath = "/config/20240923.xlsx"),   # pdata of samples includeing at least 2 col : sampleid,in  
workflow_endpoint = "3", # 1 for fastq QC; 2 for mapping ; 3 for expression/methylation matrix    
user_email = "whoami@qq.com" # email needs additional setting
)
```

### **Run Workflow**

``` r
# Process fastq files 

gandalf_RRBS$gandalf_fastq_move(method = "copy")  # another option is "move" 

# Initialize the workflow directory

gandalf_RRBS$gandalf_create_filework() 

# Write the configuration file to the workflow directory 
gandalf_RRBS$gandalf_make_config() 

# Call Snakemake to run the specified workflow 

gandalf_RRBS$gandalf2wars(
dry_run = FALSE, 
snakemake_condaenv = "snakemake", 
partition = "amd_512",
use_sbatch = FALSE)

# use_sbatch works in slurm cluster,if False,srun command will be used.
# partition param is only used in the slurm cluster mode
```

### **Aggregate Results**

``` r
# Aggregate results and compress

gandalf_RRBS$gandalf_aggResult(resultType = "matrix", method = "zip")
```

### **Update Workflow**

``` r
update_gandalf(gandalf_RRBS)
```

### **!!!CAUTION in Using BASH**

 
``` bash

export R_PROGRESSR_ENABLE=TRUE

# in Rscript

Rscript script.R > script.log 2>&1 &

#or in R

R -e "..." > script.log 2>&1 &
 
```

## **Support and Feedback**

If you encounter any issues during usage, please contact the developer via the following methods:

-   Submit GitHub Issues

## **License**

`Beaverdown2` is licensed under the MIT License.
