# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("BeaverGandalf works", {
  expect_true(inherits(BeaverGandalf, "R6ClassGenerator")) 
})
