# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand

#' Detect the computing environment (k8s, slurm, or container)
#'
#' This function attempts to determine the type of computing environment by checking for the presence
#' of specific commands associated with Kubernetes (k8s) and Slurm. If neither command is found, it
#' defaults to assuming a container environment.
#'
#' @return A character string indicating the detected environment: "k8s", "slurm", or "container".
#'
#' @export
beaver_engine_detect <- function(){
  k8s_try <- try(system(command = "kubectl version",intern = T))
  srun_try <- try(system(command = "srun -V",intern = T))
  if (class(k8s_try) != "try-error"){
    return("k8s")
  }else if (class(srun_try) != "try-error"){
    return("slurm")
  }else{
    return("container")
  }
}
