# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand

#' BeaverGandalf: A Workflow Manager for Bioinformatics Pipelines
#'
#' This R6 class manages and orchestrates bioinformatics workflows, including
#' data processing, quality control, and analysis. It supports multiple modes
#' (e.g., RRBS, BSseq, RNAseq) and can handle PDX (Patient-Derived Xenograft)
#' pipelines. The class is designed to work with Snakemake workflows and can
#' run on different computing environments (e.g., Kubernetes, Slurm).
#' @field Mode The mode of the pipeline (e.g., "RRBS", "BSSEQ", "RNASEQ").
#' @field species The species being analyzed (e.g., "human", "mouse").
#' @field species1 species1
#' @field species2  species2
#' @field host host 
#' @field cgGR_gz cgGR_gz
#' @field qcDir_before qcDir_before
#' @field qcDir_after qcDir_after
#' @field bsmapDir_bamtmp bsmapDir_bamtmp
#' @field samples A vector of sample IDs.
#' @field uploadfile A data frame containing file paths and names.11
#' @field run_log A vector storing runtime logs.
#' @field init_log A vector storing initialization logs.
#' @field yaml_file The path to the YAML configuration file.
#' @field userid A unique user ID for the workflow.
#' @field user_email The email address for notifications.
#' @field PDX_pipeline A logical indicating whether PDX mode is enabled.
#' @field fastqDir The directory for FASTQ files.
#' @field adapter1 Adapter sequences for trimming.
#' @field adapter2 Adapter sequences for trimming
#' @field CGI Paths to reference data files (e.g., CpG sites, CGI).
#' @field genomeFile Paths to genome files.
#' @field gnome_fasta Paths to genome files.
#' @field rnaseq_gtf Paths to RNAseq reference files.
#' @field rnaseq_ref Paths to RNAseq reference files.
#' @field workflow_endpoint workflow endpoint.
#' @field chrs A vector of chromosome names.
#' @field read1_5 Read trimming parameters.
#' @field read1_3 Read trimming parameters.
#' @field read2_5 Read trimming parameters.
#' @field read2_3 Read trimming parameters.
#' @field seq_deth Sequencing depth.
#' @field fixed A string indicating fixed parameters.
#' @field suffix1 Suffixes for FASTQ files.
#' @field suffix2 Suffixes for FASTQ files.
#' @field error Error rate for alignment.
#' @field C1 Alignment parameters.
#' @field C2 Alignment parameters.
#' @field T1 Alignment parameters.
#' @field T2 Alignment parameters.
#' @field graft, host Graft and host species for PDX pipelines.
#' @field pdata Phenotype data.
#' @field workflowDir  Directories for workflow, analysis, and QC.
#' @field analysisDir  Directories for workflow, analysis, and QC.
#' @field qcDir Directories for workflow, analysis, and QC.
#' @field selfconfig The directory for self-generated configuration files.
#' @field SID_log The directory for log files.
#' @field trimDir Directories for trimming, BSMAP, and methylation calling.
#' @field bsmapDir Directories for trimming, BSMAP, and methylation calling.
#' @field outDir_mCall Directories for methylation calling.
#' @field ourDirUmx Directories for UMX and Qualimap results.
#' @field outdir_qualimap Directories for UMX and Qualimap results.
#' @field outDir_mhap Directories for M-HAP and RData files.
#' @field RData_folder Directories for M-HAP and RData files.
#' @field clubcpg Directories for CpG data.
#' @field clubcpg_coverage_before Directories for CpG data.
#' @field clubcpg_model Directories for CpG data.
#' @field clubcpg_coverage_impute Directory for imputed CpG coverage.
#' @field qc_summary Directories for QC summaries and log summaries.
#' @field logsummary Directories for QC summaries and log summaries.
#' @field outDir_betaM Directories for betaM, UXM summary, and DMR results.
#' @field uxm_summary Directories for betaM, UXM summary, and DMR results.
#' @field DMR_folder Directories for betaM, UXM summary, and DMR results.
#' @field methrixh5 Directories for methrix H5 and GC bias results.
#' @field GCbias Directories for methrix H5 and GC bias results.
#' @field userspace The root directory for user workflows.
#' @method initialize initialize 
#' @method gandalf_info gandalf_info 
#' @method gandalf_fastq_move gandalf_fastq_move 
#' @method gandalf_create_filework gandalf_create_filework
#' @method gandalf_make_config gandalf_make_config
#' @method gandalf2wars gandalf2wars
#' @method gandalf_aggResult gandalf_aggResult
#' @method gandalf_process_discovery gandalf_process_discovery
#
#' @export
BeaverGandalf <- R6::R6Class(
  "BeaverGandalf",
  public = list(
    Mode = NULL, 
    suffix1 = "_R1_fastq.gz",
    suffix2 = NULL,
    error = 0.2, 
    adapter1 = "AGATCGGAAGAGC",
    adapter2 = "AGATCGGAAGAGC", 
    C1 = 0,C2 = 0,T1 = 0,T2 = 0,
    species = NULL,species1 = "human",species2 = NULL,graft = "human", host = NULL,
    read1_5 = 0,read1_3 = 0,read2_5 = 0,read2_3 = 0,seq_deth = 10,
    pdata = NULL, uploadfile = NULL, samples = NULL,workflow_endpoint = NULL,
    userid = NULL,fixed = NULL,yaml_file = NULL,
    #cgGR = "inst/hg19/hg19_CpG_sites.RData",
    cgGR_gz = "inst/hg19/hg19_CpG_sites.gz",
    CGI = "inst/hg19/hg19_cpgIsland.bed",
    gnome_fasta = c("inst/pdx/homo_sapiens/hg19.fasta",
                    "inst/pdx/mouse/GRCm38.fasta"),
    genomeFile = c("inst/pdx/homo_sapiens/",
                    "inst/pdx/mouse/"),
    rnaseq_gtf = "inst/rnaseq/homo_sapiens/hg19.ensGene_sorted.gtf",
    rnaseq_ref = "inst/rnaseq/homo_sapiens/",
    #CGIRData = "inst/hg19/hg19_CGI_GR.RData",
    #CCGG = "inst/hg19/CCGG.RData",
    #CpG  = "inst/hg19/hg19_CpG_sites.RData",
    #hg19_genomeFile = "inst/hg19/ucsc_hg19-20180821.fa",
    workflowDir   = "/workflow",
    analysisDir = "/analysis",
    selfconfig = "/config",
    qcDir      =  "/QC",
    qcDir_before      =  "/fastqc_raw",
    qcDir_after      =  "/fastqc_clean",
    SID_log =  "/log",
    trimDir =  "/trim",
    bsmapDir =  "/bsmap",
    bsmapDir_bamtmp =  "/bsmap/tmp",
    outDir_mCall =  "/mCall",
    ourDirUmx =  "/uxm",
    outdir_qualimap =  "/QC/qualimap",
    outDir_mhap =  "/mhap",
    RData_folder =  "/RData",
    clubcpg = "/clubcpg",
    clubcpg_coverage_before = "/clubcpg/clubcpg_coverage_before",
    clubcpg_model =  "/clubcpg/clubcpg_model",
    clubcpg_coverage_impute = "/clubcpg/clubcpg_coverage_impute",
    qc_summary =  "/QC",
    logsummary =   "/log",
    outDir_betaM =  "/betaM",
    uxm_summary =  "/uxm",
    DMR_folder =  "/DMR",
    methrixh5 = "/methrixh5",
    GCbias = "/GCbias",
    chrs = NULL,
    userspace = "userspace",fastqDir = NULL, PDX_pipeline = NULL,
    user_email = NULL,init_log = NULL,run_log = NULL,

#' @param Mode \code{character} The mode of the pipeline (e.g., "RRBS", "BSSEQ", "RNASEQ").
#' @param suffix1 \code{character} Suffix for the first read of paired-end FASTQ files (default: "_R1.fastq.gz").
#' @param suffix2 \code{character} Suffix for the second read of paired-end FASTQ files (default: NULL).
#' @param error \code{numeric} Error rate for alignment (default: 0.2).
#' @param adapter1 \code{character} Adapter sequence for the first read (default: "AGATCGGAAGAGC").
#' @param adapter2 \code{character} Adapter sequence for the second read (default: "AGATCGGAAGAGC").
#' @param C1 \code{numeric} Alignment parameters (default: 0).
#' @param C2 \code{numeric} Alignment parameters (default: 0).
#' @param T1 \code{numeric} Alignment parameters (default: 0).
#' @param T2 \code{numeric} Alignment parameters (default: 0).
#' @param species \code{character} or \code{NULL} Species being analyzed (default: NULL).
#' @param species1 \code{character} Primary species (default: "human").
#' @param species2 \code{character} Secondary species (default: NULL).
#' @param graft \code{character} Graft species for PDX pipelines (default: "human").
#' @param host \code{character} Host species for PDX pipelines (default: NULL).
#' @param read1_5 \code{numeric} Read trimming parameters (default: 0).
#' @param read1_3 \code{numeric} Read trimming parameters (default: 0).
#' @param read2_5 \code{numeric} Read trimming parameters (default: 0).
#' @param read2_3 \code{numeric} Read trimming parameters (default: 0).
#' @param seq_deth \code{numeric} Sequencing depth (default: 10).
#' @param pdata \code{data.frame} or \code{NULL} Phenotype data (default: NULL).
#' @param uploadfile \code{data.frame} or \code{NULL} Data frame containing file paths and names (default: NULL).
#' @param samples \code{character} or \code{NULL} Sample IDs (default: NULL).
#' @param workflow_endpoint \code{character} or \code{NULL} Workflow endpoint configuration (default: NULL).
#' @param userid \code{character} or \code{NULL} Unique user ID (default: NULL).
#' @param fixed \code{character} or \code{NULL} Fixed parameters string (default: NULL).
#' @param yaml_file \code{character} or \code{NULL} Path to the YAML configuration file (default: NULL).
#' @param cgGR_gz \code{character} or \code{NULL} Gzipped version of cgGR (default: NULL).
#' @param CGI \code{character} Path to CpG islands BED file (default: "inst/hg19/hg19_cpgIsland.bed").
#' @param gnome_fasta \code{character} or \code{vector} Path(s) to genome FASTA files (default: hg19 and GRCm38).
#' @param genomeFile \code{character} or \code{vector} Path(s) to genome files (default: hg19 and GRCm38).
#' @param rnaseq_gtf \code{character} Path to RNAseq GTF file (default: "inst/rnaseq/homo_sapiens/hg19.ensGene_sorted.gtf").
#' @param rnaseq_ref \code{character} Path to RNAseq reference directory (default: "inst/rnaseq/homo_sapiens/").
#' @param fastqDir \code{character} Directory for FASTQ files (default: "/data").
#' @param workflowDir \code{character} Directory for workflow files (default: "/workflow").
#' @param analysisDir \code{character} Directory for analysis results (default: "/analysis").
#' @param selfconfig \code{character} Directory for self-generated configuration files (default: "/config").
#' @param qcDir \code{character} Directory for quality control results (default: "/QC").
#' @param qcDir_before \code{character} Directory for raw QC results (default: "/fastqc_raw").
#' @param qcDir_after \code{character} Directory for cleaned QC results (default: "/fastqc_clean").
#' @param SID_log \code{character} Directory for log files (default: "/log").
#' @param trimDir \code{character} Directory for trimmed files (default: "/trim").
#' @param bsmapDir \code{character} Directory for BSMAP results (default: "/bsmap").
#' @param bsmapDir_bamtmp \code{character} Temporary directory for BSMAP BAM files (default: "/bsmap/tmp").
#' @param outDir_mCall \code{character} Directory for methylation calling results (default: "/mCall").
#' @param ourDirUmx \code{character} Directory for UMX results (default: "/uxm").
#' @param outdir_qualimap \code{character} Directory for Qualimap results (default: "/QC/qualimap").
#' @param outDir_mhap \code{character} Directory for M-HAP results (default: "/mhap").
#' @param RData_folder \code{character} Directory for RData files (default: "/RData").
#' @param clubcpg \code{character} Directory for CpG data (default: "/clubcpg").
#' @param clubcpg_coverage_before \code{character} Directory for pre-imputation CpG coverage (default: "/clubcpg/clubcpg_coverage_before").
#' @param clubcpg_model \code{character} Directory for CpG models (default: "/clubcpg/clubcpg_model").
#' @param clubcpg_coverage_impute \code{character} Directory for imputed CpG coverage (default: "/clubcpg/clubcpg_coverage_impute").
#' @param qc_summary \code{character} Directory for QC summaries (default: "/QC").
#' @param logsummary \code{character} Directory for log summaries (default: "/log").
#' @param outDir_betaM \code{character} Directory for betaM results (default: "/betaM").
#' @param uxm_summary \code{character} Directory for UXM summaries (default: "/uxm").
#' @param DMR_folder \code{character} Directory for DMR results (default: "/DMR").
#' @param methrixh5 \code{character} Directory for methrix H5 files (default: "/methrixh5").
#' @param GCbias \code{character} Directory for GC bias results (default: "/GCbias").
#' @param chrs \code{character} or \code{NULL} Chromosome names (default: NULL).
#' @param userspace \code{character} Root directory for user workflows (default: "userspace").
#' @param PDX_pipeline \code{logical} or \code{NULL} Whether to enable PDX pipeline mode (default: NULL).
#' @param init_log \code{character} or \code{NULL} Initialization log (default: NULL).
#' @param user_email \code{character} User email for notifications (default: "whoami").
#' @param new_userid_always \code{logical} Whether to always generate a new user ID (default: TRUE).
#'
#' @return An initialized BeaverGandalf object.
#' @export
    initialize = function(Mode = NULL, suffix1 = "_R1.fastq.gz",suffix2 = NULL,
                          error = 0.2, adapter1 = "AGATCGGAAGAGC",adapter2 = "AGATCGGAAGAGC", 
                          C1 = 0,C2 = 0,T1 = 0,T2 = 0,
                          species = NULL,species1 = "human",species2 = NULL,graft = "human", host = NULL,
                          read1_5 = 0,read1_3 = 0,read2_5 = 0,read2_3 = 0,seq_deth = 10,
                          pdata = NULL, uploadfile = NULL, samples = NULL,workflow_endpoint = NULL,
                          userid = NULL,fixed = NULL,
                          yaml_file = NULL,
                          #cgGR = "inst/hg19/hg19_CpG_sites.RData",
                          cgGR_gz = "inst/hg19/hg19_CpG_sites.gz",
                          CGI = "inst/hg19/hg19_cpgIsland.bed",
                          gnome_fasta = c("inst/pdx/homo_sapiens/hg19.fasta",
                                          "inst/pdx/mouse/GRCm38.fasta"),
                          genomeFile = c("inst/pdx/homo_sapiens/",
                                         "inst/pdx/mouse/"),
                          rnaseq_gtf = "inst/rnaseq/homo_sapiens/hg19.ensGene_sorted.gtf",
                          rnaseq_ref = "inst/rnaseq/homo_sapiens/",
                          fastqDir = "/data",
                          workflowDir   = "/workflow",
                          analysisDir = "/analysis",
                          selfconfig = "/config",
                          qcDir      =  "/QC",
                          qcDir_before      =  "/fastqc_raw",
                          qcDir_after      =  "/fastqc_clean",
                          SID_log =  "/log",
                          trimDir =  "/trim",
                          bsmapDir =  "/bsmap",
                          bsmapDir_bamtmp =  "/bsmap/tmp",
                          outDir_mCall =  "/mCall",
                          ourDirUmx =  "/uxm",
                          outdir_qualimap =  "/QC/qualimap",
                          outDir_mhap =  "/mhap",
                          RData_folder =  "/RData",
                          clubcpg = "/clubcpg",
                          clubcpg_coverage_before = "/clubcpg/clubcpg_coverage_before",
                          clubcpg_model =  "/clubcpg/clubcpg_model",
                          clubcpg_coverage_impute = "/clubcpg/clubcpg_coverage_impute",
                          qc_summary =  "/QC",
                          logsummary =   "/log",
                          outDir_betaM =  "/betaM",
                          uxm_summary =  "/uxm",
                          DMR_folder =  "/DMR",
                          methrixh5 = "/methrixh5",
                          GCbias = "/GCbias",
                          chrs = NULL,
                          userspace = "userspace",
                          PDX_pipeline = NULL,init_log = NULL,
                          user_email = "whoami",
                          new_userid_always = T) {
      # 一些不需要计算的静态配置
      message(">> Configure pipeline ...")
      init_log <- c(">> Configure pipeline ...")
      if (species1 == "homo_sapiens") stop("homo_sapiens is not allowed, use 'human' or others")
      self$Mode <- stringr::str_to_upper(Mode) 
      message(glue::glue(">> Using {self$Mode} pipeline ..."))
      init_log <- c(init_log,glue::glue(">> Using {self$Mode} pipeline ..."))
      self$user_email <- user_email
      message(glue::glue(">> Runing progress will be sent to {self$user_email} ..."))
      init_log <- c(init_log,glue::glue(">> Runing progress will be sent to {self$user_email} ..."))
      self$userspace <- userspace
      self$error <- error
      self$C1 = C1
      self$C2 = C2
      self$T1 = T1
      self$T2 = T2
      self$read1_5 = read1_5
      self$read1_3 = read1_3
      self$read2_5 = read2_5
      self$read2_3 = read2_3
      self$seq_deth = seq_deth
      self$pdata = pdata
      self$uploadfile = uploadfile
      self$genomeFile = genomeFile
      #self$cgGR = cgGR
      self$cgGR_gz = cgGR_gz
      self$CGI = CGI
      self$gnome_fasta = gnome_fasta
      self$genomeFile = genomeFile
      self$rnaseq_gtf = rnaseq_gtf
      self$rnaseq_ref = rnaseq_ref
      #self$CGIRData = CGIRData
      #self$CCGG = CCGG
      #self$CpG  = CpG
      #self$hg19_genomeFile = hg19_genomeFile
      # 一些需要计算的参数
      if (is.null(species)){
        self$species <- c(species1,species2)
      }else{
        self$species <- species
      }
      
      self$species1 <- species1
      self$species2 <- species2
      
      if (length(c(species1,species2)) <2){
        self$fixed = ""
      }else{
        self$fixed = "fixed_"
      }
      
      self$graft <- graft
      if (graft == species1){
        self$host = species2
      } else {
        self$host = species1
      }
      if (!is.null(species1) & !is.null(species2)){
        self$PDX_pipeline = T
      }else{
        self$PDX_pipeline = F
      }
      message(glue::glue(">> PDX mode is set to {self$PDX_pipeline} ..."))
      init_log <- c(init_log,glue::glue(">> PDX mode is set to {self$PDX_pipeline} ..."))
      self$suffix1 = suffix1
      if (is.null(suffix2)){
        suffix2 = gsub(1, 2, suffix1)
        if(suffix2 == suffix1){
          suffix2 = gsub(2, 1, suffix1)
        }
        self$suffix2 = suffix2
      } else{
        self$suffix2 = suffix2
      }
      message(glue::glue(">> Suffixs of raw fastq files are {self$suffix1} and {self$suffix2}."))
      init_log <- c(init_log,glue::glue(">> Suffixs of raw fastq files are {self$suffix1} and {self$suffix2}."))
      if (is.null(chrs)){
        if (graft == "human"){
          self$chrs <- paste0("chr",c(1:22))
        }else{
          self$chrs <- c(1:18) %>% as.character()
        }
      }else{
        self$chrs <- chrs
      }
      # userid in the userspace
      message(">> Create task workflows ...")
      init_log <- c(init_log,">> Create task workflows ...")
      
      gen_userid <- function(bytes = 20,task_dir){
        random_userid <- openssl::rand_bytes(bytes) %>% paste0(.,collapse = "")
        exsit_task <- list.dirs(path = task_dir,full.names = F)
        while(random_userid %in% exsit_task){
          random_userid <- openssl::rand_bytes(bytes) %>% paste0(.,collapse = "")
        }
        return(random_userid)
      }
      if (is.null(userid)){
        self$userid <- gen_userid(bytes = 20,task_dir = userspace)
      }else if(userid %in% list.dirs(path = userspace,full.names = F) & new_userid_always){
        self$userid <- gen_userid(bytes = 20,task_dir = userspace)
      }else{
        self$userid <- userid
      }
      
      message(glue::glue(">> Create Jobid:{self$userid}"))
      init_log <- c(init_log,glue::glue(">> Create Jobid:{self$userid}"))
      
      # folders
      masterDir = paste0(userspace,"/",self$userid)
      self$fastqDir = paste0(masterDir,fastqDir)
      self$workflowDir   = paste0(masterDir,workflowDir)
      self$analysisDir = paste0(masterDir,analysisDir)
      self$selfconfig = paste0(masterDir,selfconfig)
      self$yaml_file = paste0(masterDir,selfconfig,"/config.yaml")
      self$qcDir      =  paste0(masterDir,workflowDir,qcDir)
      self$qcDir_before      = paste0(masterDir,workflowDir,qcDir_before)
      self$qcDir_after      =  paste0(masterDir,workflowDir,qcDir_after )
      self$methrixh5 = paste0(masterDir,workflowDir,outDir_mCall,methrixh5)
      self$GCbias = paste0(masterDir,workflowDir,qcDir,GCbias)
      self$SID_log =  paste0(masterDir,workflowDir,SID_log)
      self$trimDir =  paste0(masterDir,workflowDir,trimDir)
      self$bsmapDir =  paste0(masterDir,workflowDir,bsmapDir)
      self$bsmapDir_bamtmp =  paste0(masterDir,workflowDir,bsmapDir_bamtmp)
      self$outDir_mCall =  paste0(masterDir,workflowDir,outDir_mCall)
      self$ourDirUmx =  paste0(masterDir,workflowDir,ourDirUmx)
      self$outdir_qualimap =  paste0(masterDir,workflowDir,outdir_qualimap)
      self$outDir_mhap =  paste0(masterDir,workflowDir,outDir_mhap)
      self$RData_folder =  paste0(masterDir,workflowDir,RData_folder)
      self$clubcpg = paste0(masterDir,workflowDir,clubcpg)
      self$clubcpg_coverage_before = paste0(masterDir,workflowDir,clubcpg_coverage_before)
      self$clubcpg_model =  paste0(masterDir,workflowDir,clubcpg_model)
      self$clubcpg_coverage_impute = paste0(masterDir,workflowDir,clubcpg_coverage_impute)
      self$qc_summary =  paste0(masterDir,qc_summary)
      self$logsummary =   paste0(masterDir,logsummary)
      self$outDir_betaM =  paste0(masterDir,analysisDir,outDir_betaM)
      self$uxm_summary =  paste0(masterDir,analysisDir,uxm_summary)
      self$DMR_folder =  paste0(masterDir,analysisDir,DMR_folder)
      # end_point
      if (workflow_endpoint == "1" ){
        temp_endpoint <- c(T,F,F)
        names(temp_endpoint) <- paste0("step",c(1:length(temp_endpoint)))
      } else if (workflow_endpoint == "2" ){
        temp_endpoint <- c(T,T,F)
        names(temp_endpoint) <- paste0("step",c(1:length(temp_endpoint)))
      }else{
        temp_endpoint <- c(T,T,T)
        names(temp_endpoint) <- paste0("step",c(1:length(temp_endpoint)))
      }
      self$workflow_endpoint <- temp_endpoint
      message(glue::glue(">> The beaverflow will be ended in step {workflow_endpoint}"))
      init_log <- c(init_log,glue::glue(">> The beaverflow will be ended in step {workflow_endpoint}"))
      # samples adapters pdata_filter uploadfiles
      message(">> Check Fastq files ...")
      
      samples <- uploadfile$name %>% 
        stringr::str_remove(.,self$suffix1) %>% 
        stringr::str_remove(.,self$suffix2) 
      
      message(glue::glue(">> Found {length(samples)} samples: {paste(samples,collapse = ',')}"))
      init_log <- c(init_log,glue::glue(">> Found {length(samples)} samples: {paste(samples,collapse = ',')}"))
      samples_paired <- samples %>% 
        {
          temp <- .
          temp_table <- table(temp)
          temp_table <- temp_table[temp_table == 2]
          names(temp_table)
        }
      message(glue::glue(">> Found {length(samples_paired )} paired_samples: {paste(samples_paired ,collapse = ',')}"))
      init_log <- c(init_log,glue::glue(">> Found {length(samples_paired )} paired_samples: {paste(samples_paired ,collapse = ',')}"))
      if (length(samples_paired) == 0){
        message(glue::glue(">> Please check your input suffix1: {self$suffix1} "))
        init_log <- c(init_log,glue::glue(">> Please check your input suffix1: {self$suffix1} "))
      }
      self$samples <- samples_paired
      self$uploadfile <- uploadfile %>% 
        dplyr::mutate(sampleid = samples) %>% 
        dplyr::filter(sampleid %in% samples_paired)
      if (!("sampleid" %in% colnames(pdata))){
        pdata <- pdata %>% 
          dplyr::mutate(sampleid = NA)
      }
      if (!("inline_barcode_sequence" %in% colnames(pdata))){
        pdata <- pdata %>% 
          dplyr::mutate(inline_barcode_sequence = NA)
      }
      
      pdata_filter <- pdata %>% 
        dplyr::filter(sampleid %in% samples_paired)
      
      self$pdata <- pdata_filter
      
      message(">> Check Phenodata ...")
      # adapter calculation
      
      trimSeq1 = rep(adapter1, length(samples_paired))
      trimSeq2 = rep(adapter2, length(samples_paired))
      for (i in 1:length(samples_paired)){
        inline_barcode_revComp = pdata_filter %>% 
          dplyr::filter(sampleid %in% samples_paired[i]) %>% 
          {
            temp <- .
            string <- revCompString(temp[["inline_barcode_sequence"]][1])
            string
          }
        if( stringr::str_to_upper(Mode)  == "RRBS"){
          trimSeq1[i] = paste0("TGA", inline_barcode_revComp, trimSeq1[i])
          trimSeq2[i] = paste0("A", inline_barcode_revComp, trimSeq2[i])
        } else {
          trimSeq1[i] = paste0(inline_barcode_revComp, trimSeq1[i])
          trimSeq2[i] = paste0(inline_barcode_revComp, trimSeq2[i])
        }
          
      }
      message(">> Calculate Adapters ...")
      self$adapter1 <- trimSeq1
      self$adapter2 <- trimSeq2
      message(">> Done!")
      self$gandalf_info()
      # complete init log for front-end display
      self$init_log <- c(init_log,">> Check Phenodata ...",
                         ">> Calculate Adapters ...",
                         ">> Done!",
                         ">>> BeaverGandalf:Hey,my dear friends!I will lead you throught the cold night of Middle-earth.")
    },
# 创建BeaverGandalf时的欢迎词
#' @usage \method{gandalf_info}{BeaverGandalf}()
#'
#' @return \code{NULL} (prints a message to the console).
#' @export
    gandalf_info = function() {
      message(">>> BeaverGandalf:Hey,my dear friends!I will lead you throught the cold night of Middle-earth.")
    },

# 从temp文件夹move文件到运行目录下
#' @param method \code{character} The method to use for file transfer. Options are:
#'   \itemize{
#'     \item \code{"copy"}: Copy the files to the workflow directory.
#'     \item \code{"move"}: Move the files to the workflow directory (default).
#'   }
#'
#' @return A data frame containing the original file paths and the new paths in the workflow directory.
#'
#' @details
#' - The method checks if the target directory exists and creates it if necessary.
#' - If a file already exists in the target directory, it will not be copied or moved again.
#' - The method logs each file transfer operation and updates the `run_log` field.
#'
    gandalf_fastq_move = function(method = c("copy","move")){
      file_df <- self$uploadfile %>% 
        dplyr::mutate(newfile_path = paste0(self$fastqDir,"/",name))
      fs::dir_create(self$fastqDir)
      for (i in 1:nrow(file_df)){
        message(glue::glue(">> processing {i}/{nrow(file_df)}"))
        self$run_log <- c(self$run_log,
                          glue::glue(">> processing {i}/{nrow(file_df)}"))
        if (method == "move"){
          if (!file.exists(file_df$newfile_path[i]))  fs::file_move(path = file_df$filepath[i],
                        new_path = file_df$newfile_path[i])
        }else if(method == "copy"){
          if (!file.exists(file_df$newfile_path[i]))  fs::file_copy(path = file_df$filepath[i],
                        new_path = file_df$newfile_path[i])
        }else{
          self$run_log <- c(self$run_log,
                            "the method should be one of copy or move")
          stop("the method should be one of copy or move")
        }
        
      }
      return(file_df)
    },

# 创建运行时需要的所有文件目录
#' Create Required Directories for the Workflow
#'
#' This method creates all necessary directories for the bioinformatics workflow.
#' It ensures that the directories for data storage, analysis results, quality control,
#' and other intermediate files are available before running the pipeline.
#'
#' @usage \method{gandalf_create_filework}{BeaverGandalf}()
#'
#' @return A character vector containing the paths of all created directories.
#'
#' @details
#' - The method creates directories for various components of the workflow, including:
#'   - User space and FASTQ files
#'   - Workflow, analysis, and QC directories
#'   - Directories for specific tools (e.g., BSMAP, Qualimap, Methrix)
#'   - Directories for intermediate and final results (e.g., CpG coverage, DMR results)
#' - If a directory already exists, it will not be recreated.
#' - The method logs each directory creation operation and updates the `run_log` field.
#'
    gandalf_create_filework = function(){
      fileworks <- c(
        self$userspace, self$fastqDir,self$workflowDir,
        self$analysisDir, self$selfconfig , self$qcDir  ,
        self$qcDir_before ,self$qcDir_after , self$methrixh5,
        self$GCbias, self$SID_log,self$trimDir ,self$bsmapDir ,
        self$bsmapDir_bamtmp,self$outDir_mCall,self$ourDirUmx,
        self$outdir_qualimap,self$outDir_mhap, self$RData_folder,
        self$clubcpg,self$clubcpg_coverage_before,self$clubcpg_model,
        self$clubcpg_coverage_impute,self$qc_summary,
        self$logsummary,  self$outDir_betaM,self$uxm_summary,
        self$DMR_folder,
        paste0(self$bsmapDir_bamtmp,"/",self$species1),
        paste0(self$bsmapDir_bamtmp,"/",self$species2),
        paste0(self$bsmapDir,"/",self$species1),
        paste0(self$bsmapDir,"/",self$species2),
        paste0(self$bsmapDir,"/Filtered_bams")
      ) %>% unique()
      
      message(glue::glue(">> Create {length(fileworks)} dirs."))
      self$run_log <- c(self$run_log,
                        glue::glue(">> Create {length(fileworks)} dirs."))
      for (i in 1:length(fileworks)){
        
        fs::dir_create(fileworks[i])
      }
      return(fileworks)
    },
# 创建snakemake运行需要的config文件
# 放在任务目录里面
#' Generate YAML Configuration File for the Workflow
#'
#' This method creates a YAML configuration file containing all necessary parameters
#' and directory paths for the bioinformatics workflow. The generated YAML file is
#' used by Snakemake or other workflow management tools to execute the pipeline.
#'
#' @usage \method{gandalf_make_config}{BeaverGandalf}()
#'
#' @return A named list containing the configuration parameters written to the YAML file.
#'
#' @details
#' - The method collects all relevant parameters from the BeaverGandalf object,
#'   including pipeline mode, species, adapter sequences, directory paths, and more.
#' - It writes these parameters to a YAML file specified by `self$yaml_file`.
#' - The method ensures that the configuration directory (`self$selfconfig`) exists
#'   before writing the file.
#' - The generated YAML file includes paths to genome files, reference data, and
#'   directories for analysis results, QC, and intermediate files.
#'

    gandalf_make_config = function(){
      
      yaml_config_list <- list(
        Mode = self$Mode,
        userid = self$userid,
        jobid = self$userid,
        species = self$species,
        graft = self$graft,
        host =self$host,
        suffix = self$suffix1,
        suffix2= self$suffix2,
        error = self$error,
        trimSeq1 = self$adapter1,
        trimSeq2 = self$adapter2,
        C1 = self$C1,
        C2 = self$C2,
        T1  = self$T1,
        T2  = self$T2,
        genomeFile = self$genomeFile,
        gnome_fasta = self$gnome_fasta,
        #hg19_genomeFile = self$hg19_genomeFile,
        #cgGR = self$cgGR,
        cgGR_gz = self$cgGR_gz,
        CGI = self$CGI,
        #CGIRData = self$CGIRData,
        #CCGG = self$CCGG,
        #CpG  = self$CpG,
        workDir = paste0(self$userspace,"/",self$userid),
        workflowDir = self$workflowDir,
        analysisDir = self$analysisDir,
        selfconfig = self$selfconfig,
        qcDir = self$qcDir ,
        qcDir_before   = self$qcDir_before,
        qcDir_after   = self$qcDir_after,
        SID_log = self$SID_log,
        trimDir = self$trimDir,
        bsmapDir = self$bsmapDir,
        bsmapDir_bamtmp = self$bsmapDir_bamtmp,
        outDir_mCall = self$outDir_mCall,
        ourDirUmx = self$ourDirUmx,
        outdir_qualimap = self$outdir_qualimap,
        outDir_mhap = self$outDir_mhap,
        RData_folder = self$RData_folder,
        DMR_folder = self$DMR_folder,
        rawDir  = self$fastqDir,
        outDir_betaM = self$outDir_betaM,
        qc_summary = self$qc_summary,
        logsummary =  self$logsummary,
        uxm_summary = self$uxm_summary,
        SIDs = self$samples,
        read1_5 = self$read1_5,
        read1_3 = self$read1_3,
        read2_5 = self$read2_5,
        read2_3 = self$read2_3,
        seq_deth = self$seq_deth,
        fixed = self$fixed,
        clubcpg = self$clubcpg,
        clubcpg_coverage_before = self$clubcpg_coverage_before,
        clubcpg_model = self$clubcpg_model,
        clubcpg_coverage_impute =  self$clubcpg_coverage_impute,
        chrs = self$chrs,
        rnaseq_gtf = self$rnaseq_gtf,
        rnaseq_ref = self$rnaseq_ref,
        methrixh5 = self$methrixh5,
        GCbias = self$GCbias,
        user_email = self$user_email,
        PDX_pipeline = self$PDX_pipeline
      )
      message(">> writing config files ...")
      self$run_log <- c(self$run_log,
                        ">> writing config files ...")
      fs::dir_create(self$selfconfig)
      yaml::write_yaml(yaml_config_list,
                       file = self$yaml_file)
      return(yaml_config_list)
      
    },
    
# 任务流程函数，实际运行的任务
#' Launch and Manage the Bioinformatics Workflow
#'
#' This method initiates and manages the execution of the bioinformatics workflow
#' using Snakemake. It supports multiple execution environments, including Kubernetes,
#' Slurm, and containerized environments. The method configures the workflow based
#' on the provided parameters and runs the pipeline in the specified mode.
#'
#' @param jobflow \code{character} The directory containing the Snakemake workflow files (default: "workflows").
#' @param enigent \code{character} The execution environment detected by \code{beaver_engine_detect()} (default: result of \code{beaver_engine_detect()}).
#' @param snakemake_condaenv \code{character} The name of the Conda environment to use for Snakemake (default: "").
#' @param dry_run \code{logical} Whether to perform a dry run without executing the workflow (default: FALSE).
#' @param partition the partition of resources used by slrum cluster,only works in slrum mode
#' @param use_sbatch \code{logical} Whether to use sbatch to submit a job or use srun in FALSE
#'
#' @return \code{NULL} (executes the workflow and logs the process).
#'
#' @details
#' - The method detects the execution environment using \code{beaver_engine_detect()}.
#' - It configures the workflow based on the environment (Kubernetes, Slurm, or container).
#' - The method runs the workflow in steps, with each step potentially involving multiple samples.
#' - Logs for each step are recorded in the \code{run_log} field.
#' - The method supports different modes (e.g., RRBS, BSSEQ, RNASEQ) and PDX pipelines.
#'
    
    gandalf2wars = function(jobflow = "workflows",
                            enigent = beaver_engine_detect(),
                            snakemake_condaenv = "",
                            dry_run = F,
                            partition = "amd_512",
                            use_sbatch = F){
      
      cpus = c("20","40","10")
      process = c("40","60","20")
      mem = c("100G","400G","400G")
      
      if (self$Mode == "RNASEQ"){
        workflow_idx = "BeaverRNA"
        job_idx = "rnaseq"
      } else if (self$PDX_pipeline){
        workflow_idx = "BeaverPDX"
        job_idx = "bsseq"
      } else {
        workflow_idx = "BeaverBS"
        job_idx = "bsseq"
      }
      
      snakemake_condaenv_bk <-  snakemake_condaenv
      if (snakemake_condaenv != ""){
        snakemake_condaenv <- paste("conda run -n ",snakemake_condaenv)
      }
      if (enigent %in% "k8s"){
        mem = paste0(mem,"i")
      }
      
      if (dry_run){
        dryrun <- "-n"
      }else {
        dryrun <- ""
      }
      
      task_df = data.frame(
        steps = paste0("step",c(1:3)),
        cpus = cpus,
        mem = mem,
        endpoint = self$workflow_endpoint
      ) %>% 
        dplyr::filter(endpoint == T)
      if (self$Mode == "RNASEQ" & nrow(task_df) == 3){
        task_df <- task_df[1:2,]
      }
      message(glue::glue(">> This workflow will be ended in step {nrow(task_df)}"))
      
      self$run_log <- c(self$run_log,
                        glue::glue(">> This workflow will be ended in step {nrow(task_df)}"))
      
      if (enigent %in% "k8s"){
        message(glue::glue(">> configure job files ... "))
        # read & write job yaml files
        for (i in 1:nrow(task_df)){
          if (task_df$steps[i] == "step1"){
            message(">> Run in Step 1")
            self$run_log <- c(self$run_log,
                              ">> Run in Step 1")
            command <- glue::glue("cd /home/builduser/beaverflow && {snakemake_condaenv} snakemake {dryrun}  --snakefile {workflow_idx}_step{i}.snakemake --configfile {self$yaml_file}")
            job_yaml <- yaml::read_yaml(file = glue::glue("workflows/{job_idx}_step{i}.yaml"))
            job_yaml$spec$template$spec$containers[[1]]$command[3] <- command
            new_job_config <- paste0(self$selfconfig,"/job_",task_df$steps[i],".yaml")
            yaml::write_yaml(job_yaml,
                             new_job_config)
            status <- system(command = glue::glue("kubectl apply -f {new_job_config}"),intern = T)
            self$run_log <- c(self$run_log,
                              status)
          }else{
            message(">> Run by per-sample in Step 2 and Step 3")
            self$run_log <- c(self$run_log,
                              ">> Run by per-sample in Step 2 and Step 3")
            configfiles <- yaml::read_yaml(self$yaml_file)
            for (a in 1:length(self$samples)){
              message(glue::glue(">> Processing sample {a}/{length(self$samples)} in step {i}"))
              self$run_log <- c(self$run_log,
                                glue::glue(">> Processing sample {a}/{length(self$samples)} in step {i}"))
              configfiles$SIDs <-  self$samples[a]
              new_yaml_config <- paste0(self$selfconfig,"/",self$samples[a],".yaml")
              yaml::write_yaml(configfiles,
                               new_yaml_config)
              command <- glue::glue("cd /home/builduser/beaverflow && {snakemake_condaenv} snakemake {dryrun} --snakefile {workflow_idx}_step{i}.snakemake --configfile {new_yaml_config}")
              job_yaml <- yaml::read_yaml(file = glue::glue("workflows/{job_idx}_step{i}.yaml"))
              job_yaml$spec$template$spec$containers[[1]]$command[3] <- command
              new_job_config <- paste0(self$selfconfig,"/job_",task_df$steps[i],"_",self$samples[a],".yaml")
              yaml::write_yaml(job_yaml,
                               new_job_config)
              status <- system(command = glue::glue("kubectl apply -f {new_job_config}"),intern = T)
              self$run_log <- c(self$run_log,
                                status)
            }
            
            message(glue::glue(">> Aggather the Results from Step {i}"))
            self$run_log <- c(self$run_log,
                              glue::glue(">> Aggather the Results from Step {i}"))
            command <- glue::glue("cd /home/builduser/beaverflow && {snakemake_condaenv} snakemake {dryrun}  --snakefile {workflow_idx}_step{i}_checker.snakemake --configfile {self$yaml_file}")
            job_yaml <- yaml::read_yaml(file = glue::glue("workflows/{job_idx}_step{i}.yaml"))
            job_yaml$spec$template$spec$containers[[1]]$command[3] <- command
            new_job_config <- paste0(self$selfconfig,"/job_",task_df$steps[i],".yaml")
            yaml::write_yaml(job_yaml,
                             new_job_config)
            status <- system(command = glue::glue("kubectl apply -f {new_job_config}"),intern = T)
            self$run_log <- c(self$run_log,
                              status)
            
          }
          }
        
      }else if (enigent %in% "container"){
        message(">> Run in container Mode")
        for (i in 1:nrow(task_df)){
          if (task_df$steps[i] == "step1"){
            message(">> Run in Step 1")
            self$run_log <- c(self$run_log,
                              ">> Run in Step 1")
            command <- glue::glue("{snakemake_condaenv} snakemake {dryrun} --snakefile {workflow_idx}_step{i}.snakemake --configfile {self$yaml_file}")
            status <- system(command = command,intern = T)
            self$run_log <- c(self$run_log,
                              status)
          }else{
            message(">> Run by per-sample in Step 2 and Step 3")
            self$run_log <- c(self$run_log,
                              ">> Run by per-sample in Step 2 and Step 3")
            configfiles <- yaml::read_yaml(self$yaml_file)
            for (a in 1:length(self$samples)){
              message(glue::glue(">> Processing sample {a}/{length(self$samples)} in step {i}"))
              self$run_log <- c(self$run_log,
                                glue::glue(">> Processing sample {a}/{length(self$samples)} in step {i}"))
              configfiles$SIDs <-  self$samples[a]
              new_yaml_config <- paste0(self$selfconfig,"/",self$samples[a],".yaml")
              yaml::write_yaml(configfiles,
                               new_yaml_config)
              command <- glue::glue("{snakemake_condaenv} snakemake {dryrun} --snakefile {workflow_idx}_step{i}.snakemake --configfile {new_yaml_config}")
              message(command)
              status <- system(command = command,intern = T)
              self$run_log <- c(self$run_log,
                                status)
            }
            message(glue::glue(">> Aggather the Results from Step {i}"))
            self$run_log <- c(self$run_log,
                              glue::glue(">> Aggather the Results from Step {i}"))
            command <- glue::glue("{snakemake_condaenv} snakemake  {dryrun} --snakefile {workflow_idx}_step{i}_checker.snakemake --configfile {self$yaml_file}")
            status <- system(command = command,intern = T)
            self$run_log <- c(self$run_log,
                              status)
          }
        }
      }else{
        
        if (use_sbatch){
          message(">> Run in Slurm cluster Mode，sbatch will be used")
          fs::dir_create(self$logsummary)
          saveRDS(self,
                  file = paste0(self$logsummary,
                                "/workflow.RDS"))
          rscript_temp <- c(
            "library(beaverdown2)",
            "library(dplyr)",
            glue::glue("BeaverGandalf <- readRDS('{self$logsummary}/workflow.RDS')"),
            "gandalf_RRBS$gandalf2wars(dry_run = F,snakemake_condaenv = '{snakemake_condaenv_bk}',use_sbatch = F)"
          )
          rfile <- paste0(self$logsummary,
                                "/workflow.R")
          writeLines(rscript_temp,
                     rfile)
          out <- paste0(self$logsummary,"/beaverflow.out")
          err <- paste0(self$logsummary,"/beaverflow.err")
          sbatch_command <- glue::glue("sbatch --ntasks=1 --cpus-per-task=2 --mem=32G  --partition={partition} --output={out} --error={err} --wrap='conda run -n base Rscript {rfile}'")
          # 运行 sbatch 提交
          message(">> Submitting Jobs by sbatch")
          system(command = sbatch_command)
          message(">> Submition Over.")
          message(">> Start watching output files")
          message(">> Run: tail -f {out}")
          
        }else{
        message(">> Run in Slurm cluster Mode，srun will be used")
        # Add sbatch support
        # sbatch --ntasks=1 --cpus-per-task=1 --mem=16G  --partition=normal --output=my_output_%j.out --error=my_error_%j.err --wrap="conda run -n base Rscript workflow.R"
        for (i in 1:nrow(task_df)){
          if (task_df$steps[i] == "step1"){
            message(">> Run in Step 1")
            self$run_log <- c(self$run_log,
                              ">> Run in Step 1")
            command <- glue::glue("srun -p {partition}  -N 1 -n 1 --cpus-per-task={task_df$cpus[i]} --mem={task_df$mem[i]} {snakemake_condaenv} snakemake  {dryrun} --snakefile {workflow_idx}_step{i}.snakemake --configfile {self$yaml_file}")
            status <- system(command = command,intern = T)
            self$run_log <- c(self$run_log,
                              status)
          }else{
            message(">> Run by per-sample in Step 2 and Step 3")
            self$run_log <- c(self$run_log,
                              ">> Run by per-sample in Step 2 and Step 3")
            configfiles <- yaml::read_yaml(self$yaml_file)
            for (a in 1:length(self$samples)){
              message(glue::glue(">> Processing sample {a}/{length(self$samples)} in step {i}"))
              self$run_log <- c(self$run_log,
                                glue::glue(">> Processing sample {a}/{length(self$samples)} in step {i}"))
              configfiles$SIDs <-  self$samples[a]
              new_yaml_config <- paste0(self$selfconfig,"/",self$samples[a],".yaml")
              yaml::write_yaml(configfiles,
                               new_yaml_config)
              command <- glue::glue("srun -p {partition}  -N 1 -n 1 --cpus-per-task={task_df$cpus[i]} --mem={task_df$mem[i]} {snakemake_condaenv} snakemake {dryrun} --snakefile {workflow_idx}_step{i}.snakemake --configfile {new_yaml_config}")
              status <- system(command = command,intern = T)
              self$run_log <- c(self$run_log,
                                status)
            }
            
            message(glue::glue(">> Aggather the Results from Step {i}"))
            self$run_log <- c(self$run_log,
                              glue::glue(">> Aggather the Results from Step {i}"))
            command <- glue::glue("srun -p {partition}  -N 1 -n 1 --cpus-per-task={task_df$cpus[i]} --mem={task_df$mem[i]} {snakemake_condaenv} snakemake  {dryrun} --snakefile {workflow_idx}_step{i}_checker.snakemake --configfile {self$yaml_file}")
            status <- system(command = command,intern = T)
            self$run_log <- c(self$run_log,
                              status)
            
          }
        }
        }
 
      }
    },
# gandalf 下载文件和结果
#' Download or Aggregate Workflow Results
#'
#' This method aggregates the results from the workflow execution and prepares
#' them for download or further analysis. It supports multiple result types and
#' compression methods.
#'
#' @param resultType \code{character} The type of result to aggregate. Options include:
#'   \itemize{
#'     \item \code{"trim"}: Trimmed FASTQ files.
#'     \item \code{"bam"}: BAM files from alignment.
#'     \item \code{"matrix"}: Methylation matrix files.
#'     \item \code{"qc"}: Quality control summary files.
#'   }
#' @param method \code{character} The compression method to use. Options include:
#'   \itemize{
#'     \item \code{"zip"}: Compress results into a ZIP archive.
#'     \item \code{"gzip"}: Compress results using gzip.
#'   }
#'
#' @return A list containing the aggregated results, including:
#'   \itemize{
#'     \item \code{rootpath}: The root directory of the results.
#'     \item \code{filedf}: A data frame with file names and paths.
#'     \item \code{compressfile}: The path to the compressed archive file.
#'   }
#'
    gandalf_aggResult =function(resultType,
                                method){
      if (resultType == "trim"){
        path = self$trimDir
      }else if (resultType == "bam"){
        path = self$bsmapDir
      }else if (resultType == "matrix") {
        path = self$outDir_mCall
      }else if(resultType == "qc"){
        path = self$qc_summary
      }else{
        stop(">> The resultType should one of the: trim,bam,matrix,qc")
      }
      
      file_list <- file_agg(path = path,
                            method = method)
      return(file_list)
      
    },
# gandalf 进度探查
#' Detect the Current Progress of the Workflow
#'
#' This method checks the current progress of the Beaverflow pipeline by examining
#' the log files in the specified log directory. It determines which steps have been
#' completed and which step is currently running.
#'
#' @usage \method{gandalf_process_discovery}{BeaverGandalf}()
#'
#' @return An integer indicating the current step number of the workflow.
#'
#' @details
#' - The method scans the log directory (`self$SID_log`) for files with the pattern
#'   `*_success.txt` to identify completed steps.
#' - It calculates the number of completed steps and determines the ongoing step.
#' - For RNAseq mode, the workflow is limited to two steps, and the method returns
#'   `2` if the second step is ongoing.
#' - For other modes, the workflow can have up to three steps, and the method returns
#'   the current step number (1, 2, or 3).
#' - The method logs the current progress using the `message` function.
#'

   gandalf_process_discovery = function(){
      log_dir <- self$SID_log
      files <- list.files(path = log_dir,
                          pattern = "*_success.txt")
      complete_steps <- length(files)
      ongoing_steps <- complete_steps + 1
       
      if (self$Mode == "RNASEQ" & ongoing_steps > 2){
        message(glue::glue(">> The Beaverflow is currently runing in step 2"))
        return(2)
      }else if (ongoing_steps > 3){
        message(glue::glue(">> The Beaverflow is currently runing in step 3"))
        return(3)
      }else {
        message(glue::glue(">> The Beaverflow is currently runing in step {ongoing_steps}"))
        return(ongoing_steps)
      }
    }
    # gandalf QC plots
    
  )
)
