# WARNING - Generated by {fusen} from dev/flat_beaverdown2.Rmd: do not edit by hand

#' detect cpu cores
#' 
#' Description
#' 
#' @return avaible cores num
#' 
#' @export
cpu_detect <- function(){
  cores <- parallel::detectCores()
  return(cores)
}
